//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_PressureLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestEdit
    {
        public int ReuestId { get; set; }
        public string Request_ID { get; set; }
        public string PatientId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public decimal Reading1_Systolic { get; set; }
        public decimal Reading1_Diastolic { get; set; }
        public Nullable<decimal> Reading2_Systolic { get; set; }
        public Nullable<decimal> Reading2_Diastolic { get; set; }
        public decimal Systolic { get; set; }
        public decimal Diastolic { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
    }
}
